# Summary {.unnumbered}

This technical report is a companion to *Do School-Based Anxiety Prevention Programs Support Youth? An Overview of Systematic Reviews with Meta-Analyses*. It documents the methods and results of our rapid overview of systematic reviews with meta-analyses on the effectiveness of anxiety prevention interventions delivered directly to students in primary and secondary school settings. We searched PubMed, ProQuest Dissertations & Theses A&I, and Social Science Premium Collection for systematic reviews that included a meta-analysis on school-based anxiety prevention interventions. Two reviewers independently screened titles and abstracts, assessed full texts for eligibility, collected data, and critically appraised systematic reviews. To estimate effectiveness and explore sources of heterogeneity for interventions delivered directly to students during normal school hours, we conducted random effects meta-analyses using data from primary studies. We identified 16 eligible systematic reviews that included 326 primary studies overall; of these, 35 primary studies evaluated 43 experimental interventions delivered directly to 17,950 students during normal school hours. The majority of these 35 primary studies were cluster-randomized trials (28 studies, 80%) and included elementary school settings (25 studies, 71%). We did not detect a statistically significant difference on risk of meeting criteria for an anxiety diagnosis between students receiving anxiety prevention interventions relative to students in control groups (risk ratio = 0.65, 95% CI [0.42 to 1.01], 95% PI [0.34 to 1.26], $I^2$ = 17%, $\tau^2$ = 0.06). Students receiving anxiety prevention interventions had lower anxiety symptoms relative to students in control groups (standardized mean difference = -0.09, 95% CI [-0.16, -0.01], 95% PI [-0.38, 0.21], $I^2$ = 18%, $\tau^2$ = 0.01). Students receiving anxiety prevention interventions also had lower depression symptoms relative to students in control groups (standardized mean difference = -0.07, 95% CI [-0.13, -0.01], 95% PI [-0.27, 0.13], $I^2$ = 0%, $\tau^2$ = 0). We did not detect a statistically significant difference on well-being between students receiving anxiety prevention interventions relative to students in control groups (standardized mean difference = -0.06, 95% CI [-0.18, 0.06], 95% PI [-0.18, 0.06], $I^2$ = 0%, $\tau^2$ = 0). We could not conduct meta-analyses for all other outcomes. Based on the findings of previous reviews and our meta-analyses, school-based anxiety prevention interventions may reduce anxiety and depression symptoms. However, we have concerns about risk of bias in this body of evidence, and effects for anxiety symptoms vary considerably due to unidentified factors. While the evidence suggests schools are more likely than not to benefit from implementing these interventions in contexts similar to those in the review, users of this evidence should be aware that current research evidence suggests both positive and negative effects are possible.