# Objectives

This technical report is a companion to *Do School-Based Anxiety Prevention Programs Support Youth? An Overview of Systematic Reviews with Meta-Analyses*. It documents the methods and results of our rapid overview of systematic reviews with meta-analyses on the effectiveness of anxiety prevention interventions delivered directly to students in primary and secondary school settings. An overview (also known as a “meta-review” or “umbrella review”) can systematically and coherently identify, collate, and synthesize systematic reviews into a single document on the best available evidence to inform policy and practice decisions (Aromataris et al., 2020; Gates et al., 2022; Pollock et al., 2022). School-based intervention is a promising approach to prevent youth anxiety (National Research Council, 2009). Schools are one of few settings where nearly all children and adolescents can be reached (Arora et al., 2019). The delivery of prevention services in the school setting importantly eliminates the many barriers that exist when families seek out mental health support, such as time, transportation, stigma around seeking mental health support, staffing shortages, and scheduling challenges (Werner-Seidler et al., 2021). Our overview aimed to assess the effects of school-based anxiety prevention interventions on anxiety diagnoses, subsyndromal anxiety, anxiety symptoms, and non-anxiety outcomes related to student well-being and educational achievement. Our overview also explored whether these effects vary by methodological, demographic, and intervention characteristics. Our goal of this overview of reviews on school-based prevention interventions is to support the decisions of education stakeholders related to the development of policies, practice guidelines, and professional preparation and continuing development programs focused on youth behavioral health.